### PR TITLE
Pin Selenium to 4.13.0

### PR DESCRIPTION
**Pull request by lugi0**

### CODE REVIEW

**Comment by mikahanninen** [comment]
Thank you for the pull request. 

For now, we like to keep selenium version under control due to existing instabilities in selenium 4 releases. Thus the exact version is in use. If you amend the version to "4.13" then we can accept your PR 😄

**Comment by lugi0** [comment]
@mikahanninen Done!

**Comment by lugi0** [comment]
@mikahanninen Thanks for updating the lock file, totally slipped my mind

**Comment by lugi0** [comment]
Any ETA on a release that includes this change?

**Comment by cmin764** [comment]
This should be [available](https://rpaframework.org/releasenotes.html) now with `rpaframework==27.5.0`.

**Pull request merged**
