### PR TITLE
Updating the Crypto file for consistency

### PR DESCRIPTION
**Pull request by TimothyLopas**
Updated the Crypto.py file for consistency in return types as well as defining a :return:

### CODE REVIEW

**Comment by TimothyLopas** [comment]
This branch includes the linting update for Archive.py.

**Comment by mikahanninen** [comment]
encoding is missing type (str)

```
        self, data: Union[bytes, str], encoding="utf-8"

```
								
[packages/main/src/RPA/Crypto.py](https://github.com/robocorp/rpaframework/blob/bcb079ba9b91416d1df6a8ca8eeec132912dd2ab/packages/main/src/RPA/Crypto.py#L235) (Line 235)

**Review by mikahanninen — CHANGES_REQUESTED** [review]
Add the one missing type hint and then this is ok.

**Review by mikahanninen — CHANGES_REQUESTED** [review]
Exclude changes to the RPA.Archive from this PR

**Comment by TimothyLopas** [comment]
Updates made as requested. Found one additional type hint for encode that also needed updating.

**Review by mikahanninen — APPROVED** [review]

**Pull request merged**
