### PR TITLE
Remove Python 3.6 support

### PR DESCRIPTION
**Pull request by osrjv**
Python 3.6 has been EOL since December and the pipeline for pip check has been failing consistently. This PR bumps the version of python to `^3.7` in all packages and removes older versions from GHA workflows.

**Note 1:** Decided to go with a looser version constraint in the library, since our robots define a strict version in conda.yaml anyways.

**Note 2:** Didn't do much testing. Shouldn't break anything, but who knows?

### CODE REVIEW

**Comment by osrjv** [comment]
Also bumped `click` to version 8 from 7, since that was breaking pip check as well.

**Comment by osrjv** [comment]
> Also bumped `click` to version 8 from 7, since that was breaking pip check as well.

Which means black had to be updated too. Oh well.

**Review by cmin764 — APPROVED** [review]
LGTM!

To unblock you on the PDF failing `test_font_serialization` test, you can put a `@pytest.mark.xfail` over it since I have no idea why that just started to fail now. Couldn't replicate on my Windows machine, but on @mikahanninen 's one is failing indeed!

```console
> poetry run pip freeze | findstr "fpdf"
fpdf2 @ file:///C:/Users/cmin/AppData/Local/pypoetry/Cache/artifacts/80/ba/5e/8c69705830e91fa651f3df75daf575e1fcc17c66773e91ff20876662a3/fpdf2-2.5.2-py2.py3-none-any.whl
```

pdf-tests-passing-windows

**Comment by cmin764** [comment]
> Reference

@osrjv [This](https://github.com/robocorp/rpaframework/pull/469#pullrequestreview-941982664) just got fixed with the latest [rpaframework-pdf](https://pypi.org/project/rpaframework-pdf/) **2.0.1**. (test [details](https://github.com/robocorp/rpaframework/pull/475#issuecomment-1100234991))

So feel free to upgrade to this in order to not have the CI passing on `pdf`.

**Pull request merged**
